import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Provider from "./provider";
import Link from "next/link";
import "@fontsource/inter";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-5`}
      >
        <div className="px-2 py-3 text-3xl uppercase font-bold bg-slate-600 rounded-xl overflow-hidden text-white">
          <Link
            href={"/"}
            className="border-2 px-2 py-1 border-white rounded-xl"
          >
            Json CRUD
          </Link>
        </div>

        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
